import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets:["latin"], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-slate-800 text-slate-300">
      <body className={`${roboto.className} h-full`}>{children}</body>
    </html>
  );
}


