import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ServerList from "@/components/Servers/ServerList";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full bg-slate-800 text-white">
      <body className={`${inter.className} h-full flex`}>
        <ServerList />
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
